### ISSUE TITLE
Build err happen

### ISSUE THREAD

**Issue by colinrs** [star-devil/vue3-ts-demo#1]
pnpm build:dev

error during build:
Error: [vite]: Rollup failed to resolve import "/mockProdServer.ts" from "/Users/xxxx/workspace/go/src/github.com/colinrs/vue3-ts-demo/src/main.ts".
This is most likely unintended because it can break your application at runtime.

**Comment by star-devil** [comment]
Thank you for reporting this issue. It has been addressed and resolved in the latest update.
